<div class="hero-unit">
    <h1>Edit Evaluation</h1>
    
<?php 
/**
 * @var \Zend\Form\Form
 */
$form = $this->form; ?>
<?php echo $this->form()->openTag($form); ?>
    <?php foreach($form->getElements() as $element) : ?>
        <?=$this->formRow($element); ?>
    <?php endforeach; ?>
    
<?php echo $this->form()->closeTag($form); ?>
    
<a href="<?=$this->url(null, array('action' => 'listevaluations', 'id' => $this->evaluation->getTest()->getId()))?>">Back</a>
</div>


