<div class="hero-unit">
    <h1>Edit Answer</h1>
    <?=$this->answer->getQuestion()->getQuestion()?> ?<br />
    
<?php 
/**
 * @var \Zend\Form\Form
 */
$form = $this->form; ?>
<?php echo $this->form()->openTag($form); ?>
    <?php foreach($form->getElements() as $element) : ?>
        <?=$this->formRow($element); ?>
    <?php endforeach; ?>
    
<?php echo $this->form()->closeTag($form); ?>
    
<a href="<?=$this->url(null, array('action' => 'listquestions', 'id' => $this->answer->getQuestion()->getTest()->getId()))?>">Back</a>
</div>


