<div class="hero-unit">
    <h1>Edit Questions</h1>
    <?=$this->test->getName()?>


        
<?php foreach($this->questions as $question):
    ?>
        <li> <h3><?=$question->getQuestion()?>  <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'editquestion', 'id' => $question->getId()))?>">
                <i class="icon-pencil"></i>Edit</a>                
            <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'deletequestion', 'id' => $question->getId()))?>">
                <i class="icon-trash"></i>Delete</a></h3> 
           
        </li>
        
<ul>    
    <?php foreach($this->answers[$question->getId()] as $answer):
    ?>
    
    <li>
       <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'editanswer', 'id' => $answer->getId()))?>">
                <i class="icon-pencil"></i>Edit</a>
       <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'deleteanswer', 'id' => $answer->getId()))?>">
                <i class="icon-trash"></i>Delete</a>
                
        <?=$answer->getAnswer()?> - <?=$answer->getPoints()?></li>
    
    <?php endforeach; //answers
    ?>
<li><a href="<?=$this->url(null, array('action' => 'editanswer',))?>?new=true&questionId=<?=$question->getId()?>""><i class="icon-pencil"></i>New Answer</a></li>    
</ul>
<?php endforeach; //questions
?>
<a href="<?=$this->url(null, array('action' => 'editquestion'))?>?new=true&testId=<?=$this->test->getId()?>">New Question<a>

    



