<div class="hero-unit">
    <h1>Edit Evaluations</h1>
    <?=$this->test->getName()?>


<ul>        
<?php foreach($this->evaluations as $evaluation):
    ?>
        <li> <h3><?=$evaluation->getSubject()?> from <?=$evaluation->getMinpercent()?>% to <?=$evaluation->getMaxpercent()?>%  <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'editevaluation', 'id' => $evaluation->getId()))?>">
                
                    <i class="icon-pencil"></i>Edit</a>                
            <a class="btn btn btn-mini" href="<?=$this->url(null, array('action' => 'deleteevaluation', 'id' =>  $evaluation->getId()))?>">
                <i class="icon-trash"></i>Delete</a></h3> 
           
        </li>
        



<?php endforeach; //questions
?>
</ul>
<a href="<?=$this->url(null, array('action' => 'editevaluation'))?>?new=true&testId=<?=$this->test->getId()?>">New Evaluation<a>

    



