<div class="hero-unit">
    <h1>Lwc Multiple Choice Demo Test</h1>
    Diese app wurde als Tutorial App für den Database First Ansatzv von Doctrine 2 im zusammenspiel mit dem Zend Framework erstellt.
    Sie erhebt derzeit keinen anspruch auf vollständigkeit daher kann noch durch mehrere features erweitert werden.
    
</div>

<div class="row">

    <div class="span4">
        <h2>Gabber of Zwabber</h2>
        <p>Bist du ein Echter Gabber oder ein Möchtegern Zwabber ?</p>
        <p><a class="btn btn-success" href="/test/test/1" target="_blank">An Test 1 Teilnehmen</a></p>
    </div>

    <div class="span4">
        <h2>Test 2 </h2>
        Gibt es noch nicht.
   </div>

   <div class="span4">
       <h2>Admin Interface</h2>
       Wird noch entwickelt.
   </div>
</div>
